

# Vector Arithmetic

In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])
y = np.array([3,4,5])

## Addition

In [5]:
print(x+y)

[4 6 8]


In [6]:
print(x+2) #scalar addition

[3 4 5]


## Subtraction

In [9]:
print(y-x)

[2 2 2]


In [ ]:
print(x+2) #scalar subtraction

## Multiplication

In [10]:
#Hadmard Product

print(x*y)

[ 3  8 15]


In [12]:
#Dot Product

print(np.dot(y,x))

26


## Division

In [14]:
#inverse 

print(y/x)

[3.         2.         1.66666667]


# Matrix Arithmetic

In [23]:
x = np.matrix([[1,2],[3,4]])
y = np.matrix([[1,3],[5,7]])
#Numpy matrices are strictly 2d , while numpy arrays (ndarrays) are N-dimensional

In [17]:
print(type(y))

<class 'numpy.matrix'>


## Addition

In [26]:
print(x,y)

[[1 2]
 [3 4]] [[1 3]
 [5 7]]


In [27]:
print(x+y)

[[ 2  5]
 [ 8 11]]


## Subtraction

In [28]:
print(x-y)

[[ 0 -1]
 [-2 -3]]


## Mutliplication

In [30]:
x = np.matrix([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [33]:
print(x*x) #Haddmard Multiplication

[[ 7 10]
 [15 22]]


In [36]:
print(np.multiply(x,x))# element wise 

[[ 1  4]
 [ 9 16]]


## Inverse

In [38]:
from numpy.linalg import inv

In [42]:
print(inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transpose

In [44]:
print(x.T) #flips rows with columns

[[1 3]
 [2 4]]
