In [3]:
import numpy as np

In [5]:
#Rank 1 array

arr1 = [3,4,5,6,7]
print(type(arr1))

<class 'list'>


In [7]:
narr1 = np.array(arr1)

In [8]:
print(type(arr1))

<class 'list'>


In [12]:
#multi-dimesnional array

arr2 = [[3,4,5,6,7],[3,4,5,6,7]]
narr2 = np.array(arr2)

print(narr2)


[[3 4 5 6 7]
 [3 4 5 6 7]]


In [15]:
#2x2 array with zeros

zer = np.zeros((2,2))
print(zer)

[[0. 0.]
 [0. 0.]]


In [16]:
ex3 = np.eye(4,4)
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
